### ISSUE TITLE
Saving LinkedInUser in _User

### ISSUE THREAD

**Issue by erad888** [alexruperez/PFLinkedInUtils#10]
It seems that the last commit, I'm having issues with `+ (void)linkUser:(PFUser *)user accessToken:(NSString *)accessToken expirationDate:(NSDate *)expirationDate profileID:(NSString *)profileID block:(PFBooleanResultBlock)block`

When you try to save linkedInUser, the block get stuck when it gets to: 

    [user setObject:linkedInUser forKey:@"linkedInUser"];
    user.password = profileID;
    [user saveInBackgroundWithBlock:block];

The problem arises when trying to set `user.password = profileID`. Using that syntax or trying `[user setPassword: profileID]` both cause `[user saveInBackgroundWithBlock:block]` to hang. 

Ths solution that I've found to work is to use the following:

    [user setObject:linkedInUser forKey:@"linkedInUser"];
    [user setObject:profileID forKey:@"password"];
    [user saveInBackgroundWithBlock:block];

Hope this helps somebody else.

**Comment by alexruperez** [comment]
I fix this in the release 0.1.6, but i can't push the pod.

http://stackoverflow.com/questions/28917651/building-a-cocoapod-with-swift-and-dependency-on-objective-c-framework
