### ISSUE TITLE
No known class method for selector 'GET:parameters:success:failure:'

### ISSUE THREAD

**Issue by lilpennyjr** [alexruperez/PFLinkedInUtils#11]
For self.LIALinkedInHttpClient, I get the following error: No known class method for selector 'GET:parameters:success:failure:'

[LIALinkedInHttpClient GET:@"URL String" parameters:nil success:^(AFHTTPRequestOperation *operation, id responseObject) {
            NSLog(@"Response JSON: %@", responseObject);
        } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
            NSLog(@"Error: %@", error);
        }];

When I include 'self.LIALinkedInHttpClient' I get the following error: Property 'LIALinkedInHttpClient' not found on object of type 'ARViewController *'

**Comment by alexruperez** [comment]
I amended the README.md, check it out. ;)
https://github.com/alexruperez/PFLinkedInUtils/commit/bc14e3c0d9ab59624483829ce9fc878ae5aed818

```objectivec
PFLinkedInUtils.linkedInHttpClient
```

**Comment by lilpennyjr** [comment]
Thanks. That resolves the error but when I build and run the app, I get
this error "*Assertion failure in -[AFHTTPRequestSerializer
requestWithMethod:URLString:parameters:error:]"*
