### ISSUE TITLE
when I build and run the app, I get this error "*Assertion failure in -[AFHTTPRequestSerializer requestWithMethod:URLString:parameters:error:]"*

### ISSUE THREAD

**Issue by lilpennyjr** [alexruperez/PFLinkedInUtils#12]
when I build and run the app, I get
this error "*Assertion failure in -[AFHTTPRequestSerializer
requestWithMethod:URLString:parameters:error:]"*

**Comment by alexruperez** [comment]
Check this http://stackoverflow.com/a/21931719
