### ISSUE TITLE
Check if LinkedIn account already linked with another existing user

### ISSUE THREAD

**Issue by jdgong** [alexruperez/PFLinkedInUtils#14]
Hi When linking LinkedIn account to current account, is there a way to check if the LinkedIn account entered is already linked with another existing user? If there is, how can I cancel the linking to avoid logging into that another user with the linked LinkedIn account? Thanks!

**Comment by alexruperez** [comment]
If you use + (void)linkUser:(PFUser *)user block:(PFBooleanResultBlock)block; method and the LinkedIn user is already linked with another Parse user, you will receive kPFErrorLinkedInAccountAlreadyLinked (308) error code.
