### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by tdunham02** [alexruperez/PFLinkedInUtils#4]
When I connect the user with LinkedIn, and then logout, and try to login with LinkedIn again, it always gives the error "LinkedIn Account Already Linked". I'm seeing that the login method always wants to create a new user, instead of just login... Am I missing something or doing something wrong?

PS. Great library, saved me a ton of time!

**Comment by alexruperez** [comment]
Fixed! Thanks for your feedback @tdunham02 :+1: 

https://github.com/alexruperez/PFLinkedInUtils/commit/03ce27ead9c02e30e7d7f786d732ac87b4a5d14f

**Comment by tdunham02** [comment]
Thanks! @alexruperez
