### ISSUE TITLE
Clear NSUserDefaults on Unlink

### ISSUE THREAD

**Issue by tdunham02** [alexruperez/PFLinkedInUtils#5]
Just a suggestion here, for something I did! After the user unlinks from LinkedIn, I clear the stored NSUserDefaults. I also do this on logout!

Added to `+ (void)unlinkUser:(PFUser *)user block:(PFBooleanResultBlock)block` after `[linkedInUser deleteInBackgroundWithBlock:block]`:

    NSUserDefaults *userDefaults = [NSUserDefaults standardUserDefaults];
    [userDefaults removeObjectForKey:LINKEDIN_TOKEN_KEY];
    [userDefaults removeObjectForKey:LINKEDIN_TOKEN_KEY];
    [userDefaults removeObjectForKey:LINKEDIN_EXPIRATION_KEY];
    [userDefaults removeObjectForKey:LINKEDIN_CREATION_KEY];
    [userDefaults synchronize];

Thanks again!

**Comment by alexruperez** [comment]
Added, thanks again @tdunham02
