### ISSUE TITLE
Callback in [PFLinkedInUtils logInWithBlock: not called when new user signs up 

### ISSUE THREAD

**Issue by RitvikM** [alexruperez/PFLinkedInUtils#8]
adding                         
block(user, nil);
below line 286 in PfLinkedInUtils seems to fix the problem 

Edit: actually that doesn't seem to resolve the problem completely. There might be other places that the callback is not being completed

**Comment by alexruperez** [comment]
Hi @RitvikM, are you using the last (0.1.5) version?

When a new user signs up correctly, the callback block is called here https://github.com/alexruperez/PFLinkedInUtils/blob/master/Pod/Classes/PFLinkedInUtils.m#L317

Can you check if you receive and error or something?

Could be a thread issue?

**Comment by pascualin** [comment]
I'm using 0.1.5 and I'm experiencing this issue as well. It all works well when an existing user signs in, but if its a new user then the block is never called.

**Comment by alexruperez** [comment]
It seems to be a problem with Parse, not calling block signUpInBackgroundWithBlock:
