### ISSUE TITLE
No known class method for selector 'signUpUserWithAccessToken:expirationDate:profileID:block:'

### ISSUE THREAD

**Issue by latsonml** [alexruperez/PFLinkedInUtils#9]
I've included the header #import "PFLinkedInUtils.h"

Yet I keep getting an error at 'signUpUserWithAccessToken'

+ (void)logInOrSignUpUserWithAccessToken:(NSString *)accessToken expirationDate:(NSDate *)expirationDate profileID:(NSString *)profileID block:(PFUserResultBlock)block
{
    if (accessToken && expirationDate && profileID)
    {
        PFQuery *profileQuery = [PFQuery queryWithClassName:@"LinkedInUser"];
        [profileQuery whereKey:@"userId" equalTo:profileID];
        
        [profileQuery findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *queryError) {
            if (!queryError)
            {
                if (objects.count == 0)
                {
                    [self signUpUserWithAccessToken:accessToken expirationDate:expirationDate profileID:profileID block:block];
                }

**Comment by alexruperez** [comment]
Hi, It works like PFFacebookUtils, the signUp method isn't public, use logIn if the user doesn't have a Parse account and you want to create one through LinkedIn, or link if the user already have an account and you want to associate it.

And remember use it [PFLinkedInUtils method...] because works with class method, instantiation is not needed.

**Comment by latsonml** [comment]
Thanks for the response. I tried using the loginWithBlock but I keep getting the error message below. Could you copy and paste the function I should use?

**Comment by alexruperez** [comment]
@latsonml try this.

If the user doesn't have a Parse account and you want to create one through LinkedIn:

```objective-c
[PFLinkedInUtils logInWithBlock:^(PFUser *user, NSError *error) {
        NSLog(@"User: %@, Error: %@", user, error);
}];
```

If the user already have an account and you want to associate it:

```objective-c
[PFLinkedInUtils linkUser:(PFUser *)user block:^(BOOL succeeded, NSError *error) {
        NSLog(Error: %@", error);
}];
```
